name: 'Install Quary CLI'
description: 'Installs the Quary CLI on Ubuntu'
branding:
  color: black
  icon: arrow-down-circle
inputs:
  version:
    description: 'Version of Quary CLI to install'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          # Fetch the latest release tag from GitHub API without authentication
          LATEST_VERSION=$(curl -s https://api.github.com/repos/quarylabs/quary-cli/releases/latest | grep 'tag_name' | cut -d '"' -f 4)
          echo "Latest version is $LATEST_VERSION"
          VERSION=$LATEST_VERSION
        else
          VERSION=${{ inputs.version }}
        fi

        echo "Installing Quary CLI version $VERSION"
        wget https://github.com/quarylabs/quary-cli/releases/download/$VERSION/quary-$VERSION-quary-linux-x86_64-gnu.zip -O quary-cli.zip
        unzip quary-cli.zip -d quary-cli
        sudo mv "quary-cli/quary /usr/local/bin/quary"
        quary --version
      shell: bash
