name: CI for Quary CLI Action

on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Install Latest Version
        uses: ./
        with:
          version: 'latest'

      - name: Test Install Specific Version
        uses: ./
        with:
          version: '0.0.67'
      - name: Verify Installation
        run: quary --version
